apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "sqs,s3,lambda,dynamodb"
            - name: DEBUG
              value: "1"
            - name: DATA_DIR
              value: "/tmp/localstack/data"
          volumeMounts:
            - mountPath: /tmp/localstack
              name: localstack-data
      volumes:
        - name: localstack-data
          emptyDir: {}

